### ISSUE TITLE
No TTS can be heard except on startup

### ISSUE THREAD

**Issue by minami-o** [CodingFree/Notifications-Reader#10]
Hi there!
Very nice add-on you have built, thanks for sharing!
Unfortunately, something prevents it from working correctly on my Flame.
Here's my setup:
- T2M Flame
- Fxos 2.5 Nightly build from Mozilla, 44.0a2
- French language (tried English (US & GB) as well, to no avail)

The only moment I can hear TTS is on startup: first I hear it in English ("Notifications service enabled"), then once or twice in French, but it seems to be stopped before the end of the text (which, I guess, is the default notification you have set), only the first 2 or 3 words are uttered.
I tried to disable the notification sound (chose "None" in "Alerts"), in case it would lock the audio channel somehow, but no better.

Now the logs, when I receive an SMS:

> W/Usage   ( 1389): Content JS WARN: SimManager is not ready, waiting for initialized custom event
> W/Usage   ( 1389):     at _requestService (app://costcontrol.gaiamobile.org/gaia_build_message_handler.js:321:281)
> W/Usage   ( 1389): Content JS WARN: The setting ril.data.defaultServiceId does not exists, using default Slot (0)
> W/Usage   ( 1389):     at _onsuccesSlotId (app://costcontrol.gaiamobile.org/gaia_build_message_handler.js:316:232)
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> D/audio_hw_primary(  200): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
> D/hardware_info(  200): hw_info_append_hw_type : device_name = speaker
> D/ACDB-LOADER(  200): ACDB -> send_audio_cal, acdb_id = 14, path =  0
> D/ACDB-LOADER(  200): ACDB -> send_adm_topology
> D/ACDB-LOADER(  200): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
> D/ACDB-LOADER(  200): ACDB -> send_asm_topology
> D/ACDB-LOADER(  200): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
> D/ACDB-LOADER(  200): ACDB -> send_audtable
> D/ACDB-LOADER(  200): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
> D/ACDB-LOADER(  200): ACDB -> AUDIO_SET_AUDPROC_CAL
> D/ACDB-LOADER(  200): ACDB -> send_audvoltable
> D/ACDB-LOADER(  200): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
> D/        (  200): Failed to fetch the lookup information of the device 0000000E
> E/ACDB-LOADER(  200): Error: ACDB AudProc vol returned = -19
> D/ACDB-LOADER(  200): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
> D/ACDB-LOADER(  200): ACDB -> send_afe_cal
> D/ACDB-LOADER(  200): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
> D/ACDB-LOADER(  200): ACDB -> AUDIO_SET_AFE_CAL
> E/GeckoConsole(  204): [JavaScript Error: "AbortError" {file: "resource://gre/modules/SettingsRequestManager.jsm" line: 401}]
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> W/AudioFlinger(  200): Thread AudioOut_2 cannot connect to the power manager service
> E/AudioFlinger(  200): no wake lock to update!
> D/hardware_info(  200): hw_info_append_hw_type : device_name = speaker

Please have a look if you can, and don't hesitate to ask for additional info/logs or tests.
Cheers,
Minami-o

**Comment by novia713** [comment]
+1
:)
